# LOOPS

## While loop

In [2]:
#the syntax of while loop
#    while *condition*
#        *loop body*
#    end
 

In [3]:
n = 0 
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
my_friends = ["Ahmed", "Fouad", "Shepl", "Ted", "chris"]

i = 1
while i <= length(my_friends)
    friend = my_friends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ahmed, it's great to see you!
Hi Fouad, it's great to see you!
Hi Shepl, it's great to see you!
Hi Ted, it's great to see you!
Hi chris, it's great to see you!


## For loop

In [5]:
# for *var* in *loop iterable*
#    *loop body*
# end

In [6]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [7]:
my_friends= ["Ahmed", "Fouad", "Shepl", "Ted", "chris"]

for friend in my_friends
    println("Hello $friend, glad to see you")
end

Hello Ahmed, glad to see you
Hello Fouad, glad to see you
Hello Shepl, glad to see you
Hello Ted, glad to see you
Hello chris, glad to see you


Creating a matrix where the elemets are the summistion of the adjacents

In [8]:
m ,n = 5, 5
A = zeros(m,n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [9]:
for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end

In [10]:
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

### or

In [11]:
for i in 1:m,j in 1:n
    A[i ,j] = i + j
end

In [12]:
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

or, we can use array comprehension

In [13]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

and we also can use array comprehension in the for loop

In [15]:
for n in 1:10
    D = [i + j for i in 1:n, j in 1:n]
    display(D)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20