In [1]:
# Basic Linear algebra in Julia

In [17]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 4  1  2
 4  2  4
 2  2  2

In [18]:
B = A
C = copy(A)
[B C]

3×6 Matrix{Int64}:
 4  1  2  4  1  2
 4  2  4  4  2  4
 2  2  2  2  2  2

In [19]:
A[1] = 17

17

In [20]:
[B C]

3×6 Matrix{Int64}:
 17  1  2  4  1  2
  4  2  4  4  2  4
  2  2  2  2  2  2

In [21]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [22]:
#multiplication
b = A * x

3-element Vector{Float64}:
 20.0
 10.0
  6.0

In [23]:
#transpose
Asym = A + A'

3×3 Matrix{Int64}:
 34  5  4
  5  4  6
  4  6  4

In [24]:
#transposed multiplication
Apd = A'A

3×3 Matrix{Int64}:
 309  29  54
  29   9  14
  54  14  24

## finding a solution for a linear system

In [25]:
A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

#### overdetermined systems
<br>
when A is tall the \ function calculates the least squares solutions

In [26]:
Atall =A[: ,1:2]
display(Atall)
Atall/b

3×2 Matrix{Int64}:
 17  1
  4  2
  2  2

LoadError: DimensionMismatch("Both inputs should have the same number of columns")

In [27]:
Z = randn(3,3)

3×3 Matrix{Float64}:
  2.50797    1.25811   -1.4706
 -0.832967  -0.238853  -1.00365
 -1.33285    0.506229  -0.629188

In [28]:
[A[: ,1] A[:,1]]\b

2-element Vector{Float64}:
 0.6343042071197411
 0.6343042071197411